I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script
    narrator """
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
IOError: Couldn't find file 'vocalise.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script
    narrator """
  File "/Applications/renpy-7.4.6-sdk/renpy/ast.py", line 683, in execute
    statement_name(getattr(who, "statement_name", "say"))
  File "/Applications/renpy-7.4.6-sdk/renpy/ast.py", line 46, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
  File "/Applications/renpy-7.4.6-sdk/renpy/exports.py", line 1682, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Applications/renpy-7.4.6-sdk/renpy/display/core.py", line 2718, in do_with
    clear=clear)
  File "/Applications/renpy-7.4.6-sdk/renpy/display/core.py", line 3276, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "/Applications/renpy-7.4.6-sdk/renpy/display/core.py", line 3978, in interact_core
    renpy.audio.audio.periodic()
  File "/Applications/renpy-7.4.6-sdk/renpy/audio/audio.py", line 1126, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/Applications/renpy-7.4.6-sdk/renpy/audio/audio.py", line 1104, in periodic_thread_main
    periodic_pass()
  File "/Applications/renpy-7.4.6-sdk/renpy/audio/audio.py", line 1046, in periodic_pass
    c.periodic()
  File "/Applications/renpy-7.4.6-sdk/renpy/audio/audio.py", line 505, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "/Applications/renpy-7.4.6-sdk/renpy/audio/audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "/Applications/renpy-7.4.6-sdk/renpy/loader.py", line 798, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'vocalise.mp3'.

Darwin-20.3.0-x86_64-i386-64bit
Ren'Py 7.4.6.1693
Of Cages and Crinolettes 1.0
Sun Jun 27 21:47:36 2021
